### ISSUE TITLE
No Audio (Besides Sound Effects.)

### ISSUE THREAD

**Issue by Pineappleguy03** [viliger2/RoR2_BobombBattlefield#1]
Love the mod. Everything seems to be spawning pretty well! The only thing I have with it is that there's no music for Bob-Omb Battlefield! All the sound effects like shaking trees, as well as he Bob-Ombs and king himself work fine. But the music is missing!

**Comment by Pineappleguy03** [comment]
INCOMPATIBLE WITH CATACOMBS MOD.

**Comment by viliger2** [comment]
This is still an issue after all. Yes, music currently breaks if you have Catacombs installed and only because Catacombs load earlier than Bobomb Battlefield. If it was the other way around then Catacombs would've not had music. It is Wwise issue and I hope to fix it in the future.
